# Generated by Django 5.2.7 on 2026-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Ödev Başlığı')),
                ('icerik', models.TextField(verbose_name='Ödev Detayı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_tarih', models.DateTimeField(verbose_name='Son Teslim Tarihi')),
                ('tamamlandi', models.BooleanField(default=False)),
            ],
        ),
    ]
